export const products = [
  {
    name: "Product item #1",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 1,
  },
  {
    name: "Product item #2",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 2,
  },
  {
    name: "Product item #3",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 3,
  },
  {
    name: "Product item #4",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 0,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 4,
  },
  {
    name: "Product item #5",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 5,
  },
  {
    name: "Product item #6",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 6,
  },
  {
    name: "Product item #7",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 7,
  },
  {
    name: "Product item #8",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 8,
  },
  {
    name: "Product item #9",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 9,
  },
  {
    name: "Product item #10",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 10,
  },
  {
    name: "Product item #11",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 11,
  },
  {
    name: "Product item #12",
    price: "R1000.00",
    description: "Lorem ipsum, dolor sit amet.",
    stock: 10,
    thumbnail: "url('./assets/product.jpg')",
    images: [],
    sizes: [],
    colors: [],
    id: 12,
  },
];
